service: lessthanonemin

frameworkVersion: '2'

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-2 # remove

functions:
  interval:
    handler: interval.handle

stepFunctions:
  stateMachines:
    everyminute:
      type: EXPRESS
      events:
        - schedule:
            rate: rate(1 minute)
      name:
        everyFiveMinutes
      definition:
        StartAt: Create Loop Items
        States:
          Create Loop Items:
            Type: Pass
            Next: Loop
            Result:
              items: [ 1, 2, 3, 4, 5, 6 ]
          Loop:
            Type: Map
            ItemsPath: "$.items"
            MaxConcurrency: 1
            Iterator:
              StartAt: Wait 10 Seconds
              States:
                Wait 10 Seconds:
                  Type: Wait
                  Seconds: 10
                  Next: Invoke Lambda
                Invoke Lambda:
                  Type: Task
                  Resource: arn:aws:states:::lambda:invoke
                  Parameters:
                    FunctionName: !GetAtt interval.Arn
                    InvocationType: Event
                  End: true
            End: true
